# -*- coding: utf-8 -*-
"""GEOPANDAS CODE 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gp7V0WnuImhqqJ4BUm_WmGpFCiCtAaRG
"""

#!pip install geodatasets

import geopandas as gpd
import matplotlib.pyplot as plt

# Load the Natural Earth countries dataset from an online source
url = 'https://raw.githubusercontent.com/python-visualization/folium/master/examples/data/world-countries.json'
world = gpd.read_file(url)

# List of South American countries
south_america = [
    'Argentina', 'Bolivia', 'Brazil', 'Chile', 'Colombia',
    'Ecuador', 'Guyana', 'Paraguay', 'Peru', 'Suriname',
    'Uruguay', 'Venezuela'
]

# Step 1: Plot the world map
fig, ax = plt.subplots(figsize=(15, 10))
world.boundary.plot(ax=ax, linewidth=1)  # Draw country boundaries

# Highlight South America countries in green and the rest in light gray
south_american_countries = world[world['name'].isin(south_america)]
south_american_countries.plot(ax=ax, color='green', edgecolor='black', label='South America')
world[~world['name'].isin(south_america)].plot(ax=ax, color='lightgray', edgecolor='black')

# Add title and legend
plt.title('World Map with South America Highlighted in Green')
plt.axis('off')  # Turn off the axis
plt.legend()
plt.show()