# -*- coding: utf-8 -*-
"""GEOPANDAS CODE 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gp7V0WnuImhqqJ4BUm_WmGpFCiCtAaRG
"""

#!pip install geodatasets

import geopandas as gpd
import matplotlib.pyplot as plt

# Load the Natural Earth countries dataset from an online source
url = 'https://raw.githubusercontent.com/python-visualization/folium/master/examples/data/world-countries.json'
world = gpd.read_file(url)

# Step 1: Plot the world map
fig, ax = plt.subplots(figsize=(15, 10))
world.boundary.plot(ax=ax, linewidth=1)  # Draw country boundaries

# Highlight Russia in red and the rest in light gray
russia = world[world['name'] == 'Russia']
russia.plot(ax=ax, color='red', edgecolor='black', label='Russia')
world[world['name'] != 'Russia'].plot(ax=ax, color='lightgray', edgecolor='black')

# Add title and legend
plt.title('World Map with Russia Highlighted in Red')
plt.axis('off')  # Turn off the axis
plt.legend()
plt.show()