# -*- coding: utf-8 -*-
"""GEOPANDAS CODE 6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gp7V0WnuImhqqJ4BUm_WmGpFCiCtAaRG
"""

#!pip install geodatasets

import geopandas as gpd
import matplotlib.pyplot as plt

# Load the Natural Earth countries dataset
url = 'https://raw.githubusercontent.com/python-visualization/folium/master/examples/data/world-countries.json'
world = gpd.read_file(url)

# List of Southeast Asian countries
southeast_asia_countries = [
    'Brunei',
    'Cambodia',
    'Indonesia',
    'Laos',
    'Malaysia',
    'Myanmar',
    'Philippines',
    'Singapore',
    'Thailand',
    'Vietnam'
]

# Step 1: Plot the world map
fig, ax = plt.subplots(figsize=(15, 10))
world.boundary.plot(ax=ax, linewidth=1)  # Draw country boundaries

# Highlight Southeast Asia countries in green
southeast_asia = world[world['name'].isin(southeast_asia_countries)]
southeast_asia.plot(ax=ax, color='green', edgecolor='black', label='Southeast Asia')

# Plot other countries in light gray
world[~world['name'].isin(southeast_asia_countries)].plot(ax=ax, color='lightgray', edgecolor='black')

# Add title and legend
plt.title('World Map with Southeast Asia Highlighted in Green')
plt.axis('off')  # Turn off the axis
plt.legend()
plt.show()