# -*- coding: utf-8 -*-
"""GEOPANDAS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gp7V0WnuImhqqJ4BUm_WmGpFCiCtAaRG
"""

#!pip install geodatasets

import geopandas as gpd
import matplotlib.pyplot as plt
from geodatasets import get_path
import pandas as pd

# Load the "nybb" dataset using geodatasets
nybb_path = get_path('nybb')
nybb = gpd.read_file(nybb_path)

# Preview the data
print(nybb.head())

print(nybb.tail())

print(nybb.describe())

print(nybb.info())

nybb.columns

# Print the data types of each column
print(nybb.dtypes)

# Map Visualization with more details
fig, ax = plt.subplots(figsize=(10, 6))
nybb.boundary.plot(ax=ax, color='black')  # Add boundaries
nybb.plot(ax=ax, column='BoroName', cmap='Set3', legend=True)  # Color by borough name
plt.title('Detailed Map of New York City Boroughs')
plt.show()

# Bar Graph: Borough areas
nybb['area_km2'] = nybb['Shape_Area'] / 1e6  # Convert area to square kilometers
fig, ax = plt.subplots(figsize=(8, 5))
nybb.plot(kind='bar', x='BoroName', y='area_km2', ax=ax, color='green')
plt.title('Borough Areas in Square Kilometers')
plt.xlabel('Borough')
plt.ylabel('Area (km²)')
plt.xticks(rotation=45)
plt.show()

# Pie Chart: Distribution of borough areas
fig, ax = plt.subplots(figsize=(6, 6))
nybb.set_index('BoroName')['area_km2'].plot.pie(ax=ax, autopct='%1.1f%%', startangle=90, cmap='Set2')
plt.title('Distribution of Borough Areas')
plt.ylabel('')  # Hide the y-axis label for pie chart
plt.show()